name: trunk_ops_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  http: ^1.2.0

  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # –ø–∞–∫–µ—Ç –¥–ª—è –Ω–∞–ª–∞—à—Ç—É–≤–∞–Ω–Ω—è –Ω–∞—Ç–∏–≤–Ω–æ–≥–æ splash-–µ–∫—Ä–∞–Ω—É
  flutter_native_splash: ^2.4.0   # (–º–æ–∂–µ—à –æ–Ω–æ–≤–∏—Ç–∏ –≤–µ—Ä—Å—ñ—é –Ω–∞ –∞–∫—Ç—É–∞–ª—å–Ω—É –ø—Ä–∏ –ø–æ—Ç—Ä–µ–±—ñ)

flutter:

  uses-material-design: true

  assets:
    - assets/icons/trunkops_logo.svg
    - assets/images/viti_logo.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 900

        - asset: assets/fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: Volja
      fonts:
        - asset: assets/fonts/volja/volja-regular_w.ttf
          weight: 400

# üîª –∫–æ–Ω—Ñ—ñ–≥ flutter_native_splash (–Ω–∞ —Ç–æ–º—É –∂ —Ä—ñ–≤–Ω—ñ, —â–æ –π `flutter:`)
flutter_native_splash:
  color: "#121613"      # —Ç–æ–π —Å–∞–º–∏–π —Ñ–æ–Ω, —â–æ –π —É —Ç–≤–æ–≥–æ –µ–∫—Ä–∞–Ω—É
  android: true
  ios: true
  web: false
  android_12:
    color: "#121613"
